#If NoCubes' custom rendering is enabled
render = true
#The color of the outline (selection box) over a smoothed block.
#Supports pretty much any format you can imagine.
#Some examples of ways to define colors:
#By name: "red"
#By name: "firebrick" (a red-orangeish color)
#By name: "gainsboro" (a light gray color)
#With RGB (red, green, blue) integers (0-255): "rgb(255, 0, 0)" (pure red)
#With RGB (red, green, blue) floats (0.0-1.0): "rgb(1.0, 0, 0)" (also pure red)
#With RGBA (red, green, blue, alpha) integers (0-255): "rgba(255, 0, 0, 0.5)" (partially transparent pure red)
#With RGBA (red, green, blue, alpha) integers (0-255): "rgba(1.0, 0, 0, 1.0)" (also partially transparent pure red)
#With hexadecimal (case insensitive) RGB (red, green, blue) integers (00-FF): "0x0ff" (aqua)
#With hexadecimal (case insensitive) RGBA (red, green, blue, alpha) integers (00-FF): "#0FF6" (partially transparent aqua)
#With HSL (hue, saturation, lightness): "hsl(270, 100%, 100%)" (a dark purple)
#With HSLA (hue, saturation, lightness, alpha): "hsla(270, 100%, 100%, 0.5)" (a partially transparent dark purple)
selectionBoxColor = "#0006"
#Similar to OptiFine's 'Better Grass' feature
#OFF - The sides of grass blocks have the default texture
#ON - The sides of grass blocks have the texture of the top of the block
betterGrassSides = false
#Similar to OptiFine's 'Better Snow' feature
#OFF - The sides of blocks nearby snow have their own texture
#ON - The sides of blocks nearby snow have the snow texture
moreSnow = false
#If small plants like flowers and grass should be moved onto NoCubes' terrain
fixPlantHeight = false
#If small tufts of grass should be rendered on top of grass blocks, similar to BetterFoliage's 'Short Grass' feature
grassTufts = false

[debug]
	#If debugging features should be enabled
	debugEnabled = false
	debugOutlineSmoothables = false
	debugVisualiseDensitiesGrid = false
	debugRenderCollisions = false
	debugRenderMeshCollisions = false
	debugRecordMeshPerformance = false
	debugOutlineNearbyMesh = false

