#Growth possibility per randomTick on a coal ore tree, a higher value means a higher possibility.
#Range: 0.0 ~ 1.0
t_coal = 0.009
#Growth possibility per randomTick on a copper ore tree, a higher value means a higher possibility.
#Range: 0.0 ~ 1.0
t_copper = 0.009
#Growth possibility per randomTick on a diamond ore tree
#Range: 0.0 ~ 1.0
t_diamond = 0.005
#Growth possibility per randomTick on an emerald ore tree
#Range: 0.0 ~ 1.0
t_emerald = 0.008
#Growth possibility per randomTick on a gold ore tree
#Range: 0.0 ~ 1.0
t_gold = 0.008
#Growth possibility per randomTick on an iron ore tree
#Range: 0.0 ~ 1.0
t_iron = 0.009
#Growth possibility per randomTick on a lapis ore tree
#Range: 0.0 ~ 1.0
t_lapis = 0.007
#Growth possibility per randomTick on a quartz ore tree
#Range: 0.0 ~ 1.0
t_quartz = 0.007
#Growth possibility per randomTick on a redstone ore tree
#Range: 0.0 ~ 1.0
t_redstone = 0.007
#Growth possibility when try to catalyze a coal ore tree, a higher value means a higher possibility.
#Range: 0.0 ~ 1.0
c_coal = 0.09
#Growth possibility when try to catalyze a copper ore tree, a higher value means a higher possibility.
#Range: 0.0 ~ 1.0
c_copper = 0.09
#Growth possibility when try to catalyze a diamond ore tree
#Range: 0.0 ~ 1.0
c_diamond = 0.04
#Growth possibility when try to catalyze an emerald ore tree
#Range: 0.0 ~ 1.0
c_emerald = 0.07
#Growth possibility when try to catalyze a gold ore tree
#Range: 0.0 ~ 1.0
c_gold = 0.07
#Growth possibility when try to catalyze an iron ore tree
#Range: 0.0 ~ 1.0
c_iron = 0.09
#Growth possibility when try to catalyze a lapis ore tree
#Range: 0.0 ~ 1.0
c_lapis = 0.07
#Growth possibility when try to catalyze a quartz ore tree
#Range: 0.0 ~ 1.0
c_quartz = 0.07
#Growth possibility when try to catalyze a redstone ore tree
#Range: 0.0 ~ 1.0
c_redstone = 0.08
#Could ore trees be planted on dirts?
dirtable = false

